custom_bbcodes_plugin:
  custom_bbcodes_enable:
    default: true
    client: true
  custom_bbcodes_list:
    client: true
    type: list
    default: 'clear|dump|float|kbd|notice|tabs'
    choices:
    - clear
    - dump
    - float
    - kbd
    - notice
    - tabs
  custom_bbcodes_resolve_references:
    default: true
    client: true
  custom_bbcodes_default_repo:
    default: "hlissner/doom-emacs"
    client: true
